In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVR 
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, balanced_accuracy_score, precision_score, recall_score, classification_report
from sklearn.preprocessing import StandardScaler


In [2]:
df=pd.read_csv("../Res/Star39552_balanced.csv")


In [3]:
df

Vmag    Plx  e_Plx    B-V SpType       Amag  TargetClass
0      10.00  31.66   6.19  1.213    K7V  22.502556            1
1       8.26   3.21   1.00  1.130  K0III  15.792525            0
2       8.27  12.75   1.06  0.596    F9V  18.797552            1
3       6.54   5.23   0.76  1.189  K1III  15.132508            0
4       8.52   0.96   0.72  0.173    B8V  13.431356            1
...      ...    ...    ...    ...    ...        ...          ...
39547   5.83   0.17   0.52  0.474  B7Iab   6.982245            0
39548   7.05  18.12   0.92  0.424    F5V  18.340790            1
39549   9.21   3.89   1.46  0.227   A1IV  17.159748            1
39550   9.01   2.13   1.46  1.467  M5III  15.651898            0
39551   9.12   3.82   0.79  0.480    F5V  17.030317            1

[39552 rows x 7 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39552 entries, 0 to 39551
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Vmag         39552 non-null  float64
 1   Plx          39552 non-null  float64
 2   e_Plx        39552 non-null  float64
 3   B-V          39552 non-null  float64
 4   SpType       39552 non-null  object 
 5   Amag         39552 non-null  float64
 6   TargetClass  39552 non-null  int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 2.1+ MB


In [23]:
#dff = df.drop(columns="SpType").copy()

In [24]:
#dff = dff[dff["e_Plx"] < 3]        

In [25]:
X = df.drop(columns="TargetClass").copy()
y = df["TargetClass"]

In [26]:
X

Vmag    Plx  e_Plx    B-V SpType       Amag
0      10.00  31.66   6.19  1.213    K7V  22.502556
1       8.26   3.21   1.00  1.130  K0III  15.792525
2       8.27  12.75   1.06  0.596    F9V  18.797552
3       6.54   5.23   0.76  1.189  K1III  15.132508
4       8.52   0.96   0.72  0.173    B8V  13.431356
...      ...    ...    ...    ...    ...        ...
39547   5.83   0.17   0.52  0.474  B7Iab   6.982245
39548   7.05  18.12   0.92  0.424    F5V  18.340790
39549   9.21   3.89   1.46  0.227   A1IV  17.159748
39550   9.01   2.13   1.46  1.467  M5III  15.651898
39551   9.12   3.82   0.79  0.480    F5V  17.030317

[39552 rows x 6 columns]

In [27]:
y

0        1
1        0
2        1
3        0
4        1
        ..
39547    0
39548    1
39549    1
39550    0
39551    1
Name: TargetClass, Length: 39552, dtype: int64

In [28]:
#labelencoder_X=LabelEncoder()
#X[:,4]=labelencoder_X.fit_transform(X[:,4])

InvalidIndexError: (slice(None, None, None), 4)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [11]:
#svc 
clfr = SVC(kernel="rbf", random_state=42)
clfr.fit(X_train, y_train)

SVC(random_state=42)

In [12]:
svc_pred = clfr.predict(X_test)

In [13]:
conf_mtx = confusion_matrix(y_test, svc_pred)
conf_mtx

array([[4113,  778],
       [ 441, 4556]], dtype=int64)

In [14]:
print(classification_report(y_test, svc_pred, labels = [1, 0]))

              precision    recall  f1-score   support

           1       0.85      0.91      0.88      4997
           0       0.90      0.84      0.87      4891

    accuracy                           0.88      9888
   macro avg       0.88      0.88      0.88      9888
weighted avg       0.88      0.88      0.88      9888



In [15]:
# random forest 
clfr = RandomForestClassifier(n_estimators=500, random_state = 42)
clfr.fit(X_train, y_train)


RandomForestClassifier(n_estimators=500, random_state=42)

In [16]:
rf_pred = clfr.predict(X_test)

In [17]:
cof_mtx = confusion_matrix(y_test, rf_pred)
cof_mtx

array([[4230,  661],
       [ 531, 4466]], dtype=int64)

In [18]:
print(classification_report(y_test, rf_pred, labels = [1, 0]))

              precision    recall  f1-score   support

           1       0.87      0.89      0.88      4997
           0       0.89      0.86      0.88      4891

    accuracy                           0.88      9888
   macro avg       0.88      0.88      0.88      9888
weighted avg       0.88      0.88      0.88      9888



In [19]:
#log reggession 
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

log_pred = logreg.predict(X_test)

In [20]:
cof_mtx = confusion_matrix(y_test, log_pred)
cof_mtx

array([[4171,  720],
       [ 512, 4485]], dtype=int64)

In [21]:
print(classification_report(y_test, log_pred, labels = [1, 0]))

              precision    recall  f1-score   support

           1       0.86      0.90      0.88      4997
           0       0.89      0.85      0.87      4891

    accuracy                           0.88      9888
   macro avg       0.88      0.88      0.88      9888
weighted avg       0.88      0.88      0.88      9888

